### ISSUE TITLE
Other options for Go

### ISSUE THREAD

**Issue by nathany** [hashrocket/websocket-shootout#9] opened 2016-09-02 18:48 UTC
Thanks for writing up the article. As a user of both Go and Elixir, it's in line with what I'd expect.

There are a few other options for Go though, which I wonder how they compare in terms of ease-of-use and performance.

https://github.com/jingweno/thunderbird
https://github.com/gorilla/websocket

Not sure if I'll have a chance to send a PR anytime soon, but if anyone else would like to, that'd be awesome.

**Comment by jboelter** [comment] 2016-09-04 07:07
Did a brief (read: ugly) conversion w/ gorilla -- noticeably faster.  May have a chance to add a gorilla version this week.

**Comment by jboelter** [comment] 2016-09-04 20:53
Added a gorilla server in the same style as the current.  Would be interesting to compare with a channel based impl like the gorilla chat example: https://github.com/gorilla/websocket/tree/master/examples/chat

Pull https://github.com/hashrocket/websocket-shootout/pull/23

**Comment by jackc** [comment] 2016-09-06 22:01
I merged the gorilla implementation.

**Comment by jackc** [comment] 2016-10-15 22:38
Finally got a chance to run all the benchmarks with all the new implementations. The new test is a little more demanding so absolute numbers are lower. Current leader is Node with uws at 26k (though that was a single run that I was unable to reproduce...) Best reproducible is Haskell at 25k. 

Gorilla came in at 20k. Normal Go websocket package came in at 22k. Not what I was expecting, but I ran the tests multiple times and these numbers seemed fairly consistent.

See results/result-02.md for the raw data.

**Closed as completed by jackc** 2016-10-15 22:38 UTC
